import yaml

from snakemake.utils import min_version, validate

min_version("9.19")


# !!!!! IMPORTANT !!!!!
# Define pathvars for all user resource files and result files
# This allows users to re-wire how the module is used in their workflow with ease.
pathvars:
    # OSM retrieval outputs by country and feature
    osm_retrieve="<resources>/retrieve",


# Load the example configuration. This will be overridden by users.
configfile: workflow.source_path("../config/config.yaml")


# Validate the configuration using the schema file.
validate(config, workflow.source_path("internal/config.schema.yaml"))


# Load internal settings separately so users cannot modify them.
with open(workflow.source_path("internal/settings.yaml"), "r") as f:
    internal = yaml.safe_load(f)

# Load python files in scripts that are used in other scripts, but not run itself.
# This is necessary for integrating the snakemake module via reference to GitHub.
workflow.source_path("scripts/_helpers.py")
workflow.source_path("scripts/_schema.py")


include: "rules/retrieve.smk"
include: "rules/network.smk"
include: "rules/plot.smk"


rule all:
    default_target: True
    input:
        rules.build_interactive_map.output,
